--
-- PostgreSQL database dump
--

-- Dumped from database version 15.6
-- Dumped by pg_dump version 16.3


DROP POLICY "Only authenticated users can access this table" ON public.wholesalers;
DROP POLICY "Only authenticated users can access the table" ON public.retailers;
DROP POLICY "Only authenticated users can access the table" ON public.orders;
ALTER TABLE ONLY public.retailers DROP CONSTRAINT retailers_wholesaler_id_fkey;
ALTER TABLE ONLY public.orders DROP CONSTRAINT orders_shop_id_fkey;
ALTER TABLE ONLY public.retailers DROP CONSTRAINT shops_pkey;
ALTER TABLE ONLY public.orders DROP CONSTRAINT orders_pkey;
ALTER TABLE ONLY public.wholesalers DROP CONSTRAINT "WholeSalers_pkey";
ALTER TABLE ONLY public.wholesalers DROP CONSTRAINT "WholeSalers_owner_phone_number_key";
ALTER TABLE ONLY public.wholesalers DROP CONSTRAINT "WholeSalers_owner_email_key";
DROP TABLE public.retailers;
DROP TABLE public.orders;
DROP TABLE public.wholesalers;
DROP SCHEMA public;
--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: wholesalers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wholesalers (
    id bigint NOT NULL,
    name character varying NOT NULL,
    address character varying,
    owner_email character varying,
    owner_phone_number bigint,
    user_id uuid DEFAULT auth.uid()
);


ALTER TABLE public.wholesalers OWNER TO postgres;

--
-- Name: WholeSalers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wholesalers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WholeSalers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    shop_id bigint,
    order_date timestamp with time zone NOT NULL,
    items text NOT NULL,
    "Last_Delivery_date" timestamp with time zone,
    order_value bigint NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: TABLE orders; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.orders IS 'contains the details of  the orders placed';


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retailers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.retailers (
    id bigint NOT NULL,
    name text NOT NULL,
    owner text NOT NULL,
    phone bigint NOT NULL,
    address text NOT NULL,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    wholesaler_id bigint,
    notes text,
    audio_note text
);


ALTER TABLE public.retailers OWNER TO postgres;

--
-- Name: TABLE retailers; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.retailers IS 'contains the details of shops and their contact information and location.';


--
-- Name: shops_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.retailers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wholesalers WholeSalers_owner_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wholesalers
    ADD CONSTRAINT "WholeSalers_owner_email_key" UNIQUE (owner_email);


--
-- Name: wholesalers WholeSalers_owner_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wholesalers
    ADD CONSTRAINT "WholeSalers_owner_phone_number_key" UNIQUE (owner_phone_number);


--
-- Name: wholesalers WholeSalers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wholesalers
    ADD CONSTRAINT "WholeSalers_pkey" PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: retailers shops_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retailers
    ADD CONSTRAINT shops_pkey PRIMARY KEY (id);


--
-- Name: orders orders_shop_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES public.retailers(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: retailers retailers_wholesaler_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retailers
    ADD CONSTRAINT retailers_wholesaler_id_fkey FOREIGN KEY (wholesaler_id) REFERENCES public.wholesalers(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: orders Only authenticated users can access the table; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Only authenticated users can access the table" ON public.orders TO authenticated USING (true);


--
-- Name: retailers Only authenticated users can access the table; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Only authenticated users can access the table" ON public.retailers TO authenticated USING (true);


--
-- Name: wholesalers Only authenticated users can access this table; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Only authenticated users can access this table" ON public.wholesalers TO authenticated USING (true);


--
-- Name: orders; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

--
-- Name: retailers; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.retailers ENABLE ROW LEVEL SECURITY;

--
-- Name: wholesalers; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.wholesalers ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE wholesalers; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.wholesalers TO anon;
GRANT ALL ON TABLE public.wholesalers TO authenticated;
GRANT ALL ON TABLE public.wholesalers TO service_role;


--
-- Name: SEQUENCE "WholeSalers_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."WholeSalers_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."WholeSalers_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."WholeSalers_id_seq" TO service_role;


--
-- Name: TABLE orders; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.orders TO anon;
GRANT ALL ON TABLE public.orders TO authenticated;
GRANT ALL ON TABLE public.orders TO service_role;


--
-- Name: SEQUENCE orders_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.orders_id_seq TO anon;
GRANT ALL ON SEQUENCE public.orders_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.orders_id_seq TO service_role;


--
-- Name: TABLE retailers; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.retailers TO anon;
GRANT ALL ON TABLE public.retailers TO authenticated;
GRANT ALL ON TABLE public.retailers TO service_role;


--
-- Name: SEQUENCE shops_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.shops_id_seq TO anon;
GRANT ALL ON SEQUENCE public.shops_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.shops_id_seq TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

